export const cars = [
  {
    id: '5',
    name: 'Koenigsegg',
    type: 'sport',
    gaz: 60,
    imageUrl: '/assets/cars/koenigsegg.png',
    numberOfPeople: 2,
    price: 300,
  },
  {
    id: '6',
    name: 'Nissan GT-R',
    type: 'sport',
    gaz: 80,
    regularPrice: 200,
    imageUrl: '/assets/cars/nissan-gtr.png',
    numberOfPeople: 2,
    price: 60,
  },
  {
    id: '7',
    name: 'Rolls - Royce',
    type: 'luxurious',
    gaz: 70,
    imageUrl: '/assets/cars/rolls.png',
    numberOfPeople: 4,
    price: 400,
  },
  {
    id: '8',
    name: 'Nissan GT-R',
    type: 'sport',
    gaz: 80,
    imageUrl: '/assets/cars/nissan-gtr.png',
    numberOfPeople: 2,
    price: 80,
  },
];
